### ISSUE TITLE
Korisnik nema mogućnost izmjene svih svojih korisničkih informacija 

### ISSUE THREAD

**Issue by acimovicAlek** [SoftverInzenjeringETFSA/SI2016_TIM1#14]
**Opis problema:** Korisnik (bilo da je prijavljen kao Individual ili Company) nema mogućnost
izmjene svih svojih korisničkih informacija, koji bi se trebali razlikovati u odnosu na to da li je
Individual ili Company.

**Commit ID:** b02fd27

**Koraci za reprodukciju problema:**
1. Pokrenuti aplikaciju Oglasi
2. Prijaviti se kao korisnik
3. Odabrati opciju Profile
4. Odabrati panel Update

**Dobiveni rezultati:** Uvijek dobijemo set istih polja za koji možemo vršiti update, a to su email.
phone i username.

**Comment by ahadzibuli1** [comment]
Ostavili smo samo ove opcije, jer smo smatrali da se ime i prezime ne moze mijenjati.
